### ISSUE TITLE
FactoryApp.xml missing

### ISSUE THREAD

**Issue by githubuser0xFFFF** [grotius-cnc/Skynet_Robot_Control_Rtos_Ethercat#2]
Hi,

I'm just playing around with your software and I have to say it is really impressive what you have created. I noticed, that you use a `FactoryApp.xml` file in your video and screenshot. This file is missing in the repository. Would it be possible to add this file as an example to make it easier to get started?

Would be great. 

Thank you for this cool project. It really helps to  learn how to use opencascade and robot kinematic.

**Comment by grotius-cnc** [comment]
Hi,

The FactoryApp.xml file is autogenerated by the running program. Some release's have no FactoryApp.xml anymore.
