### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by devds** [grotius-cnc/Skynet_Robot_Control_Rtos_Ethercat#3]
Hi, can you help me to compile this project?
Many thanks in adavance
Let me know

**Comment by grotius-cnc** [comment]
Hi,

Excuse me for late reply.

Are you on linux? Did you already install qt? 
Did you installed the opencascade library and  the orocos kinematics library ?

Normally we open the .pro file and do "cntr +r" to compile (build) the project.

Let me know how far you are in trying out.
